import { StyleSheet, Platform } from 'react-native';
import { COLORS } from './colors';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.white },
  containerPrimary: { flex: 1, backgroundColor: COLORS.primary },
  scrollContent: { flexGrow: 1, paddingBottom: 40 },
  center: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  row: { flexDirection: 'row', alignItems: 'center' },
  rowBetween: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },

  headerTitle: { fontSize: 28, fontWeight: 'bold', color: COLORS.black, marginBottom: 8 },
  headerSubtitle: { fontSize: 16, color: '#6B7280', marginBottom: 24 },
  sectionTitle: { fontSize: 18, fontWeight: 'bold', color: COLORS.black, marginBottom: 12 },
  label: { fontSize: 14, fontWeight: '600', color: '#374151', marginBottom: 8, marginTop: 16 },
  text: { fontSize: 16, color: COLORS.black },
  textGray: { fontSize: 14, color: COLORS.gray },
  link: { color: COLORS.primary, fontWeight: 'bold', textDecorationLine: 'underline' },

  input: {
    backgroundColor: COLORS.inputBg,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 16,
    color: COLORS.black,
    marginBottom: 15,
  },
  inputError: { borderColor: COLORS.error },

  primaryButton: {
    backgroundColor: COLORS.primary,
    paddingVertical: 16,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  primaryButtonText: { color: COLORS.white, fontSize: 16, fontWeight: 'bold' },
  secondaryButton: {
    paddingVertical: 16,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.white,
  },
  secondaryButtonText: { color: '#374151', fontSize: 16, fontWeight: '600' },
  outlineButton: {
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.error,
  },
  outlineButtonText: { color: COLORS.error, fontWeight: '600', fontSize: 16 },
  disabledButton: { opacity: 0.6 },

  card: {
    backgroundColor: COLORS.white,
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#F3F4F6',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  cardLarge: {
    backgroundColor: COLORS.white,
    borderRadius: 20,
    padding: 25,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
  },

  navHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: Platform.OS === 'ios'? 20: 40,
    paddingHorizontal: 20,
    paddingBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
    backgroundColor: COLORS.white,
  },
  backButtonText: { fontSize: 16, color: '#6B7280' },

  authHeader: {
    height: '40%',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.primary,
  },
  authFormWrapper: {
    flex: 1,
    backgroundColor: COLORS.white,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    overflow: 'hidden',
  },
  authFormContent: { paddingHorizontal: 30, paddingTop: 40, alignItems: 'center' },
  authTitle: { fontSize: 16, color: COLORS.primary, fontWeight: '500', marginBottom: 30 },

  badge: { backgroundColor: '#F3F4F6', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 12 },
  badgeText: { color: COLORS.black, fontWeight: '600' },

  tabContainer: { flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: '#E5E7EB', marginBottom: 20 },
  tab: { marginRight: 24, paddingBottom: 12 },
  tabActive: { borderBottomWidth: 2, borderBottomColor: COLORS.primary },
  tabText: { fontSize: 16, color: '#6B7280', fontWeight: '500' },
  tabTextActive: { color: COLORS.primary, fontWeight: 'bold' },

  emptyState: { alignItems: 'center', paddingVertical: 40 },
  emptyTitle: { fontSize: 18, fontWeight: 'bold', color: '#374151', marginTop: 16 },
  emptySubtitle: { fontSize: 14, color: '#6B7280', textAlign: 'center', marginTop: 8, paddingHorizontal: 40 },

  avatar: { width: 60, height: 60, borderRadius: 30, backgroundColor: '#F3F4F6' },
  avatarLarge: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#F0F0F0',
    justifyContent: 'center',
    alignItems: 'center',
  },

  genderContainer: { flexDirection: 'row', gap: 12 },
  genderButton: {
    flex: 1,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 12,
    alignItems: 'center',
    backgroundColor: COLORS.white,
  },
  genderActive: { backgroundColor: COLORS.primary, borderColor: COLORS.primary },
  genderText: { fontSize: 16, fontWeight: '500', color: '#6B7280' },
  genderTextActive: { color: COLORS.white },

  toggleButton: {
    width: 80,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: '#E5E7EB',
    alignItems: 'center',
  },
  toggleActive: { backgroundColor: COLORS.success },
  toggleText: { fontWeight: '600', color: '#4B5563' },
  toggleTextActive: { color: COLORS.white },
});